---
layout: post
title: “歡迎來到卡巴內羅 - 哪裡有人喜歡熱”
categories: 博客
author_picture: https://avatars2.githubusercontent.com/u/50369766
author_github: https://github.com/Kabanero-io
seo-title: 歡迎來到Kabanero

seo-description: Kabanero是一個開源項目，專注於以精心設計的方式匯集幾種基礎開源技術...

blog_description: “Kabanero是一個開源項目，專注於以精心設計的方式匯集幾種基礎開源技術...”

language: zh-TW
---
= 歡迎來到Kabanero  - 有些人喜歡它
Alan Little <https://github.com/Kabanero-io>

歡迎來到Kabanero開源項目，我們的目標是為在Kubernetes上構建應用程序的體驗增添一些認真的味道。我們的項目專注於簡化架構，開發，部署和管理雲原生應用程序的任務，使用定制的應用程序堆棧和與開源協調工作的緊密集成的工具。

Kabanero將基礎開源技術集成到基於微服務的現代框架中，用於在Kubernetes上構建應用程序。企業今天提供的用於提供IT功能的開源技術數量非常龐大。 Kabanero減少了複雜的選擇，但保留了靈活性。 Kabanero使架構師能夠設計和定義，開發人員可以更自信地編寫代碼，運營商可以高效地進行管理。

該行業已經融合了卡巴內羅所接受的兩個關鍵原則：

*必須使用容器化中間件構建容器化應用程序。
* Kubernetes是新應用程序的基礎容器編排環境。




我們今天在整個組織中發現Kabanero為Champ，Jane和Todd設計的三個角色。

冠軍“建築師”（企業，解決方案或應用程序）

Champ負責確保其公司的整體架構保持在一起，並且管理業務應用程序以滿足公司和行業法規。他正在尋找適用於他所選語言，運行時和工具的一致性和靈活性。這降低了培訓成本，使開發人員能夠在項目之間移動。 Champ旨在為Jane和Todd提供少量應用程序堆棧，使其能夠高效地構建和管理應用程序。他希望推動公司的應用領域向前發展，並使他和他的前任代表公司進行的重大投資現代化。

Jane“已建立的Java開發人員”



托德“運營商”

Todd負責運營Kubernetes平台和Jane生產的應用程序。他的重點是定制一套自動化管道，以確保應用程序滿足他運行他負責的系統的需求。 Todd還負責監控系統並確保他能夠滿足公司或業務部門設定的可用性要求。 Todd通過使用一套標準和自動化來保證持續合規性，確保開發團隊與將代碼交付到生產中之間的平穩過渡。

== 我們目前關注的是什麼......

中央Kabanero概念是應用程序堆棧。應用程序堆棧定義Jane將用於開發應用程序的運行時和框架。它還包括可用於學習如何構建這些應用程序的教育材料，示例和文檔。這充滿了在Kubernetes上部署的專業知識，包括安全性，規模，健康和活力。應用程序堆棧是Todd安裝的實體，Champ在與Jane共享之前進行策劃。


應用程序堆棧將包括Jane的應用程序模板以及為Jane的代碼提供運行時（以及更多）的經過認證的基本容器映像。 Champ負責將他批准的應用程序堆棧本地策劃到Application Hub中。我們將在即將發布的博客文章中撰寫更多相關信息。





將代碼檢入Git會導致webhook被啟動;這個webhook導致CI / CD管道啟動 - 這是Kabanero提供的集成和自動化應用程序生命週期的一部分。默認情況下，我們使用Tekton管道來管理部署生命週期。 Tekton是一個Kubernetes本地開源項目，用於創建CI / CD管道，源自Knative項目。更多細節將在稍後的博客中討論，包括如何插入其他CI / CD選項。


Jane使用的應用程序堆棧由Champ設置，使得容器以Kubernetes Special Interest Group for Applications規定的方式構建。這允許Kabanero的一個名為Application Navigator的組件為應用程序的所有部分提供管理視圖。它使得一起工作的容器組能夠由Todd和Jane一起可視化和管理。

== 請繼續關注，我們剛剛開始

隨著項目的進展，你會看到我們在開放式建設中。我們將為每個關鍵人物角色介紹更多主題。以下是一些未來的主題：

*教育指南和样本
*可用於構建應用程序的運行時和語言
*有關應用程序中心的詳細信息以及Champ管理它的工作流程
*如何驗證應用程序的安全性
* API如何集成到流中並進行管理

繼續與我們聯繫。您將看到該網站充滿了指南，代碼和其他博客。同時，在Twitter上關注我們，或加入我們的懶散渠道，告訴我們您的想法或想要了解更多內容！
