---
layout: post
title : "Kabanero에 오신 것을 환영합니다."
categories: blog
author_picture: https://avatars2.githubusercontent.com/u/50369766
author_github: https://github.com/Kabanero-io
seo-title : 카바 네로에 오신 것을 환영합니다.

seo-description : Kabanero는 잘 짜여진 방식으로 여러 가지 기초적인 오픈 소스 기술을 결합하는 데 초점을 맞춘 오픈 소스 프로젝트입니다.

blog_description : "Kabanero는 잘 설계된 방식으로 여러 가지 기본 오픈 소스 기술을 통합하는 데 초점을 맞춘 오픈 소스 프로젝트입니다 ..."

language: ko
---
= Kabanero에 오신 것을 환영합니다.
Alan Little <https://github.com/Kabanero-io>



Kabanero는 근본적인 오픈 소스 기술을 Kubernetes에서 응용 프로그램을 빌드하기위한 현대적인 마이크로 서비스 기반 프레임 워크로 통합합니다. 오늘날 IT 기능을 제공하는 기업의 오픈 소스 기술의 수는 압도적입니다. Kabanero는 복잡한 선택을 줄이고 유연성을 유지합니다. Kabanero는 건축가가 설계 및 정의 할 수있게 해주 며, 개발자는 자신있게 코드를 더 빨리 작성하고 운영자는 효율적으로 관리 할 수 ​​있습니다.

업계는 Kabanero가 포용하는 두 가지 핵심 원칙에 수렴했습니다.

컨테이너 화 된 미들웨어로 컨테이너 애플리케이션을 구현하는 것이 필수적입니다.
* Kubernetes는 새로운 응용 프로그램을위한 컨테이너 오케스트레이션 환경입니다.




현재 Kabanero는 Champ, Jane 및 Todd를 위해 설계된 조직을 통해 세 명의 인물을 찾습니다.

챔피언 "건축가"(엔터프라이즈, 솔루션 또는 응용 프로그램)

Champ는 회사의 전반적인 아키텍처가 함께 유지되고 비즈니스 응용 프로그램이 회사 및 산업 규정을 준수하도록 관리 할 책임이 있습니다. 그는 선택한 언어, 런타임 및 도구에 적용되는 일관성과 유연성을 찾고 있습니다. 이를 통해 교육 비용을 줄이고 개발자가 프로젝트간에 이동할 수 있습니다. Champ는 Jane과 Todd에게 응용 프로그램 스택을 효율적으로 구축하고 관리 할 수있는 소수의 응용 프로그램 스택을 제공하고자합니다. 그는 회사의 자산을 앞으로 옮기고 그와 그의 전임자가 회사를 대신하여 막대한 투자를 현대화하기를 원합니다.

Jane "기존 Java 개발자"

Jane은 기존 응용 프로그램 서버용 Java, Java EE 및 Spring 응용 프로그램을 개발하는 데 능숙합니다. Jane은 클라우드 고유의 응용 프로그램과 서비스의 잠재력을 최대한 활용하기 위해 새로운 언어와 프레임 워크를 배우려합니다. 그녀의 역할은 그녀가 애플리케이션 로직, 비즈니스 로직 및 기본 인프라에 집중해야한다는 것입니다. 그녀는 끊임없이보다 빠른 속도와 높은 품질로 코드를 제공해야한다는 압력에 시달리고 있습니다. Champ의 목표는 Jane이 승인 된 애플리케이션 스택을 제공하여 Jane이 Kubernetes 용 애플리케이션을 개발할 수있게하는 것입니다.
































