---
layout: post
title: “欢迎来到卡巴内罗 - 哪里有人喜欢热”
categories: blog
author_picture: https://avatars2.githubusercontent.com/u/50369766
author_github: https://github.com/Kabanero-io
seo-title: 欢迎来到Kabanero

seo-description: Kabanero是一个开源项目，专注于以精心设计的方式汇集几种基础开源技术...

blog_description: “Kabanero是一个开源项目，专注于以精心设计的方式汇集几种基础开源技术...”

language: zh-CH
---
= 欢迎来到Kabanero  - 有些人喜欢它
Alan Little <https://github.com/Kabanero-io>



Kabanero将基础开源技术集成到基于微服务的现代框架中，用于在Kubernetes上构建应用程序。企业今天提供的用于提供IT功能的开源技术数量非常庞大。 Kabanero减少了复杂的选择，但保留了灵活性。 Kabanero使架构师能够设计和定义，开发人员可以更自信地编写代码，运营商可以高效地进行管理。

该行业已经融合了卡巴内罗所接受的两个关键原则：

*必须使用容器化中间件构建容器化应用程序。
* Kubernetes是新应用程序的基础容器编排环境。

Kabanero团队根据角色的需求进行了基于角色的设计思考。我们从这些设计思维会议中测试了我们的假设，这些假设来自正在迁移到云的旅程中的企业用户。我们发现的现状是不符合这些客户期望的结果，我们提出的未来状态大大改善了他们在人物角色之间转移责任时遇到的问题。这使他们相信Kabanero将帮助团队更快地构建软件，为云部署做好准备，并适应当今组织的结构，并使他们更有效地提供代码。


我们今天在整个组织中发现Kabanero为Champ，Jane和Todd设计的三个角色。

冠军“建筑师”（企业，解决方案或应用程序）

Champ负责确保其公司的整体架构保持在一起，并且管理业务应用程序以满足公司和行业法规。他正在寻找适用于他所选语言，运行时和工具的一致性和灵活性。这降低了培训成本，使开发人员能够在项目之间移动。 Champ旨在为Jane和Todd提供少量应用程序堆栈，使其能够高效地构建和管理应用程序。他希望推动公司的应用产业向前发展，并使他和他的前任为公司所做的重大投资现代化。

Jane“已建立的Java开发人员”

Jane擅长为传统应用程序服务器开发Java，Java EE和Spring应用程序。 Jane热衷于学习新的语言和框架，以充分利用云原生应用程序和服务的全部潜力。她的角色要求她专注于应用程序逻辑，业务逻辑和底层基础架构。她一直面临着以更快的速度和更高的质量提供代码的压力。 Champ的目标是为Jane提供他批准的应用程序堆栈，以使Jane能够为Kubernetes开发应用程序。

托德“运营商”



== 我们目前关注的是什么......

中央Kabanero概念是应用程序堆栈。应用程序堆栈定义Jane将用于开发应用程序的运行时和框架。它还包括可用于学习如何构建这些应用程序的教育材料，示例和文档。这充满了在Kubernetes上部署的专业知识，包括安全性，规模，健康和活力。应用程序堆栈是Todd安装的实体，Champ在与Jane共享之前进行策划。


应用程序堆栈将包含Jane的应用程序模板以及为Jane的代码提供运行时（以及更多）的经过认证的基本容器映像。 Champ负责将他批准的应用程序堆栈本地策划到Application Hub中。我们将在即将发布的博客文章中撰写更多相关信息。










== 请继续关注，我们刚刚开始

隨著項目的進展，你會看到我們在開放式建設中。我們將為每個關鍵人物角色介紹更多主題。以下是一些未來的主題：

*教育指南和样本
*可用於構建應用程序的運行時和語言
*有關應用程序中心的詳細信息以及Champ管理它的工作流程
*如何驗證應用程序的安全性
* API如何集成到流中並進行管理

繼續與我們聯繫。您將看到該網站充滿了指南，代碼和其他博客。同時，在Twitter上關注我們，或加入我們的懶散渠道，告訴我們您的想法或想要了解更多內容！









