---
layout: post
title: "Kabanero World Tour Begins!"
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/50876789
author_github: https://github.com/erpenbach
seo-title: Kabanero.io - Kabanero World Tour Begins!
seo-description: Kabanero is on a World Tour in September.  Check out the different venues where it can be found and how it can simplify the move to a container and Kubernetes environment. 
blog_description: "Kabanero is on a World Tour in September.  Check out the different venues where it can be found and how it can simplify the move to a container and Kubernetes environment."
---
= Kabanero World Tour Begins!
Eric Erpenbach <https://github.com/erpenbach>
Kabanero World Tour Begins!

The momentum around Kabanero is continuing to grow as the word is spreading on how it tackles the complexities of developing, deploying, and managing solutions in a Kubernetes environment.   Kabanero is now taking to the world stage to give developers more chances to experience this simplifying technology.  

It all starts on September 9 in Hursley, England, at the https://community.ibm.com/community/user/imwuc/events/event-description?CalendarEventKey=c050d0e7-e8dc-4b22-bb15-34745c34cab7[European Application, Platform & Modernization Summit]. At this event Kabanero will take center stage in the discussions on moving existing applications to the cloud.  

Next stop is at the https://2019.javazone.no/[JavaZone] conference September 11-12 in Oslo, Norway.  At this conference, Kabanero will be showcased at the expo floor with attendees given the opportunity to try Kabanero out first hand.  If you want a sneak peek, there is also a https://www.meetup.com/IBM-Cloud-Norway/events/264053468/[meetup] in Oslo on September 10 where you can get a more intimate experience of Kabanero. 

That same week, Kabanero will also make an appearance at the https://summit.ithome.com.tw/kubernetes/[Taiwan Kubernetes Summit] as part of the keynote address.  In that session, the advantages of developing Kabanero in the community will be discussed along with the role it plays in strategies for transforming solutions to cloud native formats. 

Then, September 16-19, Kabanero will be at the center of a number of sessions at the annual https://www.oracle.com/code-one/[Oracle Code One] conference. Look for sessions DEV6686 and DEV3080 as they cover how Kabanero streamlines the development of cloud native applications.  At the event, attendees will also be able to try Kabanero out as well as talk to experts on the capabilities and features making Kabanero the right foundation for moving an enterprise to the cloud.  

Finally, the month of September finishes with Kabanero appearing at the inaugural https://developer.ibm.com/events/ibm-application-modernization-technical-conference-2019-na-chicago-09-24-2019-09-25-2019/[Application Modernization Technical Conference], hosted by IBM, in Chicago, September 24-25.  Here will be another opportunity to learn more about why Kabanero is a key part in the move to the cloud.  There will be deep dives into the complexities of modernizing the enterprise and the best path for addressing these with Kabanero.

Hopefully you’ll be able to attend one of these events.  If not, no worries, as Kabanero will be adding more stops to its World Tour in October.   

Of course, you can always https://kabanero.io/try-it[give Kabanero] a try and have your own personal experience at any time too.
