---
layout: post
title: "What's New in Release 0.7.0"
categories: blog
author: Jeff Antley
author_picture: https://avatars3.githubusercontent.com/u/50876789
author_github: https://github.com/jantley-ibm
additional_authors:
 - name: Stephen Kinder
   image: https://avatars3.githubusercontent.com/u/50876789
   github: https://github.com/stephenkinder

seo-title: What is new in release 0.7.0
seo-description: "Read about changes in Kabanero 0.7.0."
blog_description: "Read about changes in Kabanero 0.7.0."
---

We are excited to present the latest release of Kabanero, version 0.7.0. We have a lot of changes to tell you about.

== Open Liberty Operator

Kabanero 0.7 introduces the Open Liberty Operator, which is a specialization of the Appsody Operator. The Open Liberty Operator extends deployment capabilities that expose Open Liberty Environment Variables; Persistent Volume support for logs, traces and dumps; and day 2 features like requesting server dumps and traces. Developers have the same development experience, but gain access to those specific Open Liberty features. 

Check out the link:https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.md#overview[Open Liberty Operator docs] to learn more about it.

== GitHub protocol

The Kabanero Custom Resource is extended to express Github protocol access for assets stored in Github. This alternative to the existing HTTPS makes secure access to your assets easier.

== Pipeline development flexibility

The Kabanero operator now allows the specification of pipelines as a single file that contains the pipeline assets, rather than having to package individual files in a zip. This change simplifies the pipeline development experience.

== User experience

We've added the CodeReady Workspace tile to the user experience to provide quick links for easy access. We've also added a new admin management feature to help you manage your stack hub admins via the Console UI. For more release information, check out the link:https://github.com/kabanero-io/kabanero-landing/releases/tag/0.7.0[console's 0.7.0 release in GitHub].

== System management CLI and service

The CLI client includes several usability enhancements and fixes:
. Improved clarity of which stacks are obsolete. 
. Reduced the number of usage/help messages that appear in the CLI related to expired credentials or non-user related errors. 
. Fixed a CLI client segfault issue that occurs when trying to connect to environments that need a VPN but the VPN is not enabled. 

== Blocking and Tackling

As usual, we've updated the foundation components to stay current.

Dependent open source components

[%header,cols=2*]
|===
|Component
|Version

|Appsody Operator
|0.3.0

|OpenShift Pipelines Operator
|0.10.4

|OpenShift Serverless Operator
|1.4.1

|OpenShift ServiceMesh Operator
|1.0.8

|Open Liberty Operator
|0.3.0

|Tekton Dashboard
|0.5.2

|===

Remember, the community has moved away from a Kabanero "branded Che" and towards the CodeReady variant to make the developer experience more consistent with Kabanero and OCP. The version of the CodeReady Workspaces Operator varies depending on OCP release.

== Environments

Kabanero 0.7.0 executes on OCP 4.3.

== Stacks

The curated stack hub is located here: https://github.com/kabanero-io/kabanero-stack-hub/releases/tag/0.7.0

[%header,cols=2*]
|===
|Stack
|Version

|java-openliberty
|0.2.3

|java-spring-boot2
|0.3.24

|nodejs
|0.3.3

|nodejs-express
|0.2.10

|java-microprofile
|0.2.26 (in the process of deprecation)
|===
