---
layout: post
title: "What's New in Release 0.8.0"
categories: blog
author: Jeff Antley
author_picture: https://avatars3.githubusercontent.com/u/50876789
author_github: https://github.com/jantley-ibm
additional_authors:
 - name: Stephen Kinder
   image: https://avatars3.githubusercontent.com/u/50876789
   github: https://github.com/stephenkinder

seo-title: What is new in release 0.8.0
seo-description: "Read about changes in Kabanero 0.8.0."
blog_description: "Read about changes in Kabanero 0.8.0."
---

We proudly present version 0.8.0 of Kabanero. We have some exciting updates to tell you about.

== Digest governance policy

Kabanero 0.8 implements governance policy, which can be used to ensure that only the active application stacks are being used to build microservices, and that the microservices being deployed are built from those same active application stacks. Documentation which provides application tagging and digest best practices is delivered. Four styles of policy allow for variation in enterprise container tag management. The Dashboard, CLI, REST APIs*, and Kabanero operator all enhanced to support governance and enhanced views and displays for container digests.  For version 0.8, we have implemented two governance policy detection points: pre-build and post-build.

(*) The REST APIs have a limitation for digest retrieval and checks: digest processing is only supported for containers hosted in Docker Hub, to be addressed in a future milestone.

== Pipeline security

TLS enabled calls to SKOPEO.

== Blocking and Tackling

As usual, we've updated the foundation components to stay current.

Dependent open source components

[%header,cols=2*]
|===
|Component
|Version

|Appsody Operator
|0.4.0

|OpenShift Pipelines Operator
|0.10.8

|OpenShift Serverless Operator
|1.5.0

|OpenShift ServiceMesh Operator
|1.0.8

|Open Liberty Operator
|0.4.0

|Tekton Dashboard/Webhook-Extension
|0.5.3

|===

Remember, the community has moved away from a Kabanero "branded Che" and towards the CodeReady variant to make the developer experience more consistent with Kabanero and OCP. The version of the CodeReady Workspaces Operator varies depending on OCP release.

== Environments

Kabanero 0.8.0 executes on OCP 4.3.

== Stacks

The curated stack hub is located here: https://github.com/kabanero-io/kabanero-stack-hub/releases/tag/0.8.0

[%header,cols=2*]
|===
|Stack
|Version

|java-openliberty
|0.2.3

|java-spring-boot2
|0.3.28

|nodejs
|0.3.3

|nodejs-express
|0.2.10

|java-microprofile
|0.2.26 (in the process of deprecation)
|===
