---
layout: post
title：「カバネロへようこそ - 暑いところが好き」
categories: blog
author_picture：https://avatars2.githubusercontent.com/u/50369766
author_github：https://github.com/Kabanero-io
seo-title：カバネロへようこそ

seo-description：Kabaneroは、いくつかの基本的なオープンソーステクノロジをうまく設計された方法でまとめることに焦点を絞ったオープンソースプロジェクトです...

blog_description：「Kabaneroは、いくつかの基本的なオープンソーステクノロジをうまく設計された方法でまとめることに焦点を絞ったオープンソースプロジェクトです...」

language: ja
---
= Kabaneroへようこそ - 暑いところが好きです
アランリトル<https://github.com/Kabanero-io>

Kabaneroオープンソースプロジェクトへようこそ。ここでは、Kubernetesでアプリケーションを構築する経験に真剣な味を追加することを目的としています。調整されたアプリケーションスタックと、オープンソースと調和して機能する緊密に統合されたツール。

Kabaneroは、Kubernetesでアプリケーションを構築するための基本的なオープンソーステクノロジを、最新のマイクロサービスベースのフレームワークにまとめました。 IT機能を提供するために今日企業が持っているオープンソース技術の数は圧倒的です。カバネロは複雑な選択を減らしますが、それでも柔軟性を保ちます。 Kabaneroを使用すると、設計者は設計と定義を行うことができ、開発者は自信を持って素早くコードを書くことができ、オペレータは効率的に管理することができます。

業界は、カバネロが採用している2つの重要な原則に集中しています。

コンテナ化されたミドルウェアを使ってコンテナ化されたアプリケーションを構築することは必須です。
* Kubernetesは、新しいアプリケーションの基盤となるコンテナオーケストレーション環境です。

Kabaneroチームは、関与する役割の必要性についてペルソナベースのデザイン思考をしました。私たちは、クラウドへの移行を検討している企業のユーザーとのこれらのデザイン思考セッションからの仮説を検証しました。現状のままであると我々が判断したものはこれらの顧客の望ましい結果を満たしていない、そして我々の提案される予定の状態はペルソナ間で責任を移すことで彼らが遭遇した問題を劇的に改善した。これにより、Kabaneroはチームが迅速にソフトウェアを構築し、クラウド展開の準備が整い、今日の組織の構造に適したものになり、コードをより効率的に配布できるようになると確信しました。


Kabaneroが設計されているのは今日、組織全体で3つのペルソナ、つまり、Champ、Jane、およびToddです。

チャンプ「建築家」（エンタープライズ、ソリューションまたはアプリケーション）

Champは、彼の会社の全体的なアーキテクチャーをまとめ、ビジネスアプリケーションが会社および業界の規制を満たすように管理されていることを確認する責任があります。彼は自分の選んだ言語、ランタイム、そしてツールに適用される一貫性と柔軟性を探しています。これによりトレーニングコストが削減され、開発者はプロジェクト間を移動できます。 Champは、ジェーンとトッドに、効率的なアプリケーションの構築と管理を可能にする少数のアプリケーションスタックを提供しようとしています。彼は、会社のアプリケーション分野を前進させ、彼と彼の前任者が会社のために行った多大な投資を近代化したいと考えています。

Jane「確立されたJava開発者」



トッド「オペレーター」

Toddは、KubernetesプラットフォームとJaneによって作成されたアプリケーションの運用を担当しています。彼の焦点は、一連の自動化パイプラインを調整して、自分が担当するシステムを実行するためのアプリケーションのニーズを確実に満たすことです。 Toddは、システムを監視し、自分の会社または事業部門によって設定された可用性要件を確実に満たすことができるようにする責任を負います。継続的なコンプライアンスを維持するための自動化。

== 現在注目しているのは...

カバネロの中心となる概念はアプリケーションスタックです。アプリケーションスタックは、Janeがアプリケーションの開発に使用するランタイムとフレームワークを定義します。また、彼女がこれらのアプリケーションを構築する方法を学ぶために使用できる教材、サンプル、および資料も含まれています。これには、セキュリティ、規模、健全性、活気など、Kubernetesへの展開に関する専門知識が注ぎ込まれています。


アプリケーションスタックには、Janeのアプリケーション用のテンプレートと、Janeのコード用のランタイム（およびそれ以上のもの）を提供する認定ベースコンテナイメージの両方が含まれます。 Champは、承認されたアプリケーションスタックをローカルにApplication Hubに整理する責任があります。これについては、今後のブログ記事で詳しく説明します。


最初からKubernetesのコンテナでアプリケーションを開発するために、ホストされた開発環境で作業しているチーム向けに、VS Code、Eclipse、Eclipse Cheなどの人気のある開発者IDEへの拡張を提供するEclipse Codewindを選択しました。 Janeは、自分が好むツールを使用して、両方の新しいアプリケーションを構築することも、既存のアプリケーションを最新化することもできます。最初からコンテナ内部で内部ループが発生するため、チェックイン時にJaneが自分のコードに自信を持ちやすくなります。その後、Janeは自分のコードをGitにチェックインして、プロセスの次の段階が始まります。


コードをGitにチェックインすると、Webフックが開始されます。このWebフックによってCI / CDパイプラインが開始されます。これは、Kabaneroが提供する統合および自動化されたアプリケーションライフサイクルの一部です。デフォルトでは、展開のライフサイクルを管理するためにTektonパイプラインを使用します。 Tektonは、Knativeプロジェクトに由来する、CI / CDパイプラインを作成するためのKubernetes固有のオープンソースプロジェクトです。他のCI / CDオプションをプラグインする方法を含む詳細は、後のブログで議論されるでしょう。


Champによって設定された、Janeによって使用されるアプリケーションスタックは、Kubernetes Special Interest Group for Applicationsによって規定された方法でコンテナを構築するようにします。これにより、アプリケーションナビゲータと呼ばれるKabaneroのコンポーネントは、アプリケーションのすべての部分に管理ビューを提供できます。 ToddとJaneによって、連携して動作するコンテナのグループを視覚化してまとめて管理することができます。

== しばらくお待ちください、開始したばかりです

プロジェクトが進むにつれて、私たちはオープンになっていくのを見るでしょう。私たちの主要人物のそれぞれについて、さらに多くのトピックを紹介します。これが来ているいくつかのトピックはここにあります：

*教育ガイドとサンプル
*アプリケーションの構築に使用できるランタイムと言語
* Application Hubの詳細と、それを管理するためのChampのワークフロー
*アプリケーションのセキュリティ検証方法
どのようにAPIがフローに統合され、管理されているか

チェックインしてください。サイトにガイド、コード、その他のブログが掲載されています。その間は、Twitterでフォローするか、スラックチャンネルに参加して、あなたがどう思うか、もっと知りたいかを教えてください。
